### ISSUE TITLE
Switching to standard

### ISSUE THREAD

**Issue by ElectrumDevelopment** [jrendel/SwiftKeychainWrapper#101]
let deviceID = KeychainWrapper.defaultKeychainWrapper.string(forKey:"userID") as String!

Thats what my code is right now.

If I switch to let deviceID = KeychainWrapper.standard.string(forKey:"userID") as String!
will it be an empty key?

**Comment by crashoverride777** [comment]
No, it will not be an empty key, it will return the same value as before
