### ISSUE TITLE
Submit Pod to CocoaPods

### ISSUE THREAD

**Issue by AndreasBoehm** [jrendel/SwiftKeychainWrapper#11]
The process is described here: http://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Comment by jrendel** [comment]
Going to get to this once I'm happy with the Access Group stuff. Still need to dig some more into proper unit testing. But I've gotten started on it by getting my pod spec to validate at least.

**Comment by cipriancaba** [comment]
+1

**Comment by wjiuxing** [comment]
++

**Comment by jrendel** [comment]
Sorry this took so long to do. I didn't realize how simple it was or I would have done it sooner! I just have been swamped at work and haven't looked at this project in awhile. But its now in the official cocoa pods repo.
