### ISSUE TITLE
Remove the Keychain data on App uninstalling.

### ISSUE THREAD

**Issue by tushar666** [jrendel/SwiftKeychainWrapper#110]
Guys i want to erase all the stored value from Keychain once the app is uninstalled.

**Comment by edward-sentongo** [comment]
That can't be done. Once user wants to install app, you get no call backs notifying you about uninstall

**Comment by NikKovIos** [comment]
Use UserDefaults instead.

**Comment by jrendel** [comment]
As has been mentioned, this cannot be done automatically, but there are some options to handle clearing it on the next re-install and first run as @marcus604 mentioned.
