### ISSUE TITLE
Swift Package Manager / XCode11 support

### ISSUE THREAD

**Issue by SlashDevSlashGnoll** [jrendel/SwiftKeychainWrapper#127]
Are there plans to support SPM?  Xcode 11 now supports SPM for all project types and will soon become the desired method for managing dependencies.

**Comment by m0n9oose** [comment]
@SlashDevSlashGnoll #131

**Comment by SlashDevSlashGnoll** [comment]
Good deal!

**Comment by ralcr** [comment]
Hi, i forked the repository and converted it to swift package,  you can use this url https://github.com/ralcr/SwiftKeychainWrapper with branch develop. There are few tests failing but my guess is it's because of the new setup.

**Comment by legolasW** [comment]
@ralcr  Sadly your branch seems not working with SPM as well. Could you please have a look at it?


Showing All Messages
: https://github.com/ralcr/SwiftKeychainWrapper.git has no Package.swift manifest for version 3.4.0

**Comment by ralcr** [comment]
@legolasW It works but you need to use the branch develop instead version 3.4.0

**Comment by thejeff77** [comment]
Would love to see this merged soon :)

**Comment by akshitzaveri** [comment]
Thanks @ralcr

**Comment by jrendel** [comment]
Hey guys, sorry for not keeping up with this repo. I've just pushed a 4.0 to CocoaPods with a bunch of PRs merged, including support for SPM.
