### ISSUE TITLE
Pod is broken on latest commits

### ISSUE THREAD

**Issue by bbsan2k** [jrendel/SwiftKeychainWrapper#13]
Hey,
just wanted to notify you that your podspec is broken for latest commits.

Cocoapods: 0.36.3
XCode: 6.3
Swift: 1.2

**Comment by speakerbug** [comment]
I'm also having this exact same issue.

**Comment by jrendel** [comment]
Try it now guys. The pod should be on 1.0.9 and should work for you. Let me know if its working. The pod spec passes validation and I was able to get it running on my test project:

https://github.com/jrendel/SwiftKeychainWrapperExample

**Comment by Jaakko-Samuli** [comment]
my Cocoapods(0.36.4) says: [!] Unable to find a specification for `SwiftKeychainWrapper`

cocoapods.ord search can't find it either: https://cocoapods.org/?q=SwiftKeychainWrapper

**Comment by ryanio** [comment]
+1 for cocoapods not being able to find a specification

**Comment by AndreasBoehm** [comment]
The problem is that you are using it the wrong way. i dont know why but jrendel hasnt registered this project on the cocoapods repository. to use this project with cocoapods you need to use this line in your podfile

```
pod 'SwiftKeychainWrapper', :git => 'https://github.com/jrendel/SwiftKeychainWrapper', :branch => 'master'
```

**Comment by ryanio** [comment]
Ah got it, thanks @AndreasBoehm. @jrendel would be awesome if you could add it to the cocoapods repository when you get a chance!

**Comment by jrendel** [comment]
Alright guys, I've pushed this project to the official cocoa pods repo so you should be able to access it now just with pod 'SwiftKeychainWrapper' in your podfile.
