### ISSUE TITLE
iOS 12/13 deprecations

### ISSUE THREAD

**Issue by m0n9oose** [jrendel/SwiftKeychainWrapper#137]
### Steps to reproduce:
1. Create new iOS application
2. Set deployment target to iOS 13

### Expected result:
No deprecation warnings.

### Actual result:

1. `KeychainItemAccessibility.swift:109:18: 'kSecAttrAccessibleAlways' was deprecated in iOS 12.0: Use an accessibility level that provides some user protection, such as kSecAttrAccessibleAfterFirstUnlock`
2. `KeychainItemAccessibility.swift:111:33: 'kSecAttrAccessibleAlwaysThisDeviceOnly' was deprecated in iOS 12.0: Use an accessibility level that provides some user protection, such as kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly`
3. `KeychainWrapper.swift:203:34: 'unarchiveObject(with:)' was deprecated in iOS 12.0: Use +unarchivedObjectOfClass:fromData:error: instead`
4. `KeychainWrapper.swift:289:36: 'archivedData(withRootObject:)' was deprecated in iOS 12.0: Use +archivedDataWithRootObject:requiringSecureCoding:error: instead`

**Comment by romeugodoi** [comment]
This issue is still happening

**Comment by markusloffler** [comment]
Same here...

**Comment by Th5192** [comment]
I also am experiencing this problem.  May I ask why this issue was closed?  I apologize in advance if I am doing something wrong in GitHub.  I'm a noob and still trying to figure out how things work.

@jrendel thank you for creating this awesome SwiftKeychainWrapper!

**Comment by Th5192** [comment]
Same here...

@jrendel thank you for creating this awesome SwiftKeychainWrapper!

**Comment by dinotrnka** [comment]
This warning is happening to me too. Can we expect a fix?

**Comment by jamesjmtaylor-dexcom** [comment]
Still happening as of 2023.
