### ISSUE TITLE
Copyright statement

### ISSUE THREAD

**Issue by ptclarke** [jrendel/SwiftKeychainWrapper#16]
MIT copyright
My understanding is that the MIT copyright statement included in the project needs to be included in the code to be in effect, as it stands the code is copyrighted by yourself with no mention of the MIT copyright.

**Comment by jrendel** [comment]
Ah thanks for the heads up. I'll try and get this cleaned up this weekend.

**Comment by ptclarke** [comment]
Thanks, that would be appreciated!
