### ISSUE TITLE
Calling stringForKey sometimes returns nil for keys that previously worked

### ISSUE THREAD

**Issue by bedaronco** [jrendel/SwiftKeychainWrapper#21]
I'm getting some strange behavior when accessing data.  I have a static method that I use to retrieve  a stored auth token for an API call.  This static method is called a couple times and returns the data I expect.  From one of my view controllers though it's returning nil.

I make the exact same call for the exact same keys.  Two calls return data and the last one does not.  I'm getting a return status of -34018.  I'm not sure what that error code is.

**Comment by hgwhittle** [comment]
I'm seeing the same issue.

**Comment by bedaronco** [comment]
This looks like a bug in iOS and only when running in the debugger.  I'm seeing some discussions elsewhere saying they see the same thing.  When I run outside of the debugger I don't ever see the problem.  Very strange and quite annoying.

**Comment by hgwhittle** [comment]
Does anyone know of a workaround?

**Comment by bedaronco** [comment]
I have not seen one.  Lots of people saying reboot your device and then try.  That does seem to occasionally work.  Nothing seems permanent though.

**Comment by kanekin** [comment]
Does it happen when the app is in background? If so it could be related to this: http://stackoverflow.com/questions/10536859/ios-keychain-not-retrieving-values-from-background/10583042#10583042

**Comment by jrendel** [comment]
Also see this issue if its related to the background issue: https://github.com/jrendel/SwiftKeychainWrapper/issues/29

**Comment by DennisDreissen** [comment]
I'm also (still) having this issue. Is there any fix for this?

**Comment by JuanPabloBoero** [comment]
Anyone suffering from this issue, please do a clean install and **ALSO** remove all keychain objects, and try again, i think it is something with the overwriting.

The method is not yet on the class, but there is a Issue covering it:[Remove all  objects method](https://github.com/jrendel/SwiftKeychainWrapper/issues/28)

**Comment by jrendel** [comment]
Was this issue originally occurring only on the simulator? I'm seeing a similar issue this year running on the iOS 10 simulator. https://github.com/jrendel/SwiftKeychainWrapper/issues/59

Going to close this issue.
