### ISSUE TITLE
Saving JSON object in KeyChain

### ISSUE THREAD

**Issue by sumairasaeed** [jrendel/SwiftKeychainWrapper#24]
I want to save a JSON object in Keychain with DataType JSON without changing it to string.
Please help how to save a json object in keychain using this library?

**Comment by jrendel** [comment]
If the JSON object implements NSCoding, you can save it using setObject(value: NSCoding, forKey keyName: String).

If not, you could archive it to NSData first and save it using setData(value: NSData, forKey keyName: String).
