### ISSUE TITLE
hasValueForKey Return nil in background state 

### ISSUE THREAD

**Issue by mosn** [jrendel/SwiftKeychainWrapper#29]
When application in background state, `hasValueForKey` return `nil` therefore it is not possible to query for existing value when app is in background state. 

Is there any workaround for this or am I doing something wrong?

**Comment by jrendel** [comment]
The wrapper is currently set to only be accessible while the phone is unlocked. This could be affecting it. If you want to test you can change line 184 from kSecAttrAccessibleWhenUnlocked to one of the other constants that would allow access even when locked. However, just be aware that by doing that you may be circumventing the security offered by using keychain in the first place.

**Comment by mosn** [comment]
@jrendel Thanks very much for the update, That did the trick.
