### ISSUE TITLE
KeychainWrapper with Swift Compiler optimizations "Fastest"

### ISSUE THREAD

**Issue by matthewvermaak** [jrendel/SwiftKeychainWrapper#4]
When packaging up a release IPA (IE: for testflight) KeychainWrapper.stringForKey() returns a nil value. It passes without error, but the value is blank.

For instance:

    KeychainWrapper.setString("APPLE", forKey: "FRUIT")
    var fruit = KeychainWrapper.stringForKey("FRUIT")
    var alert:UIAlertView = UIAlertView(title: "FRUIT", message: "\(fruit)", delegate: self, cancelButtonTitle: "Ok")
    alert.show()

Took a lot of searching, but I stumbled across: http://stackoverflow.com/questions/26355630/swift-keychain-and-provisioning-profiles

Disabling the optimizations for the release target remedied the problem, but I am wondering if there is something that can be done to fix whatever is breaking when optimized away. (Might just have to wait for an apple fix?)

**Comment by andrewebling** [comment]
I've had the same problem with another keychain wrapper (PAKeychainService), which I've forked and fixed with an internal Objective-C wrapper to do the read: https://github.com/andrewebling/PAKeychainService/blob/master/KeychainObjCWrapper.m

**Comment by jrendel** [comment]
Thanks for the suggestion @andrewebling. I've taken a similar approach and added my own KeychainObjcWrapper to handle this issue. My fix is currently in the develop branch and I'll release it to master soon.

I've made other changes along with this one to support CocoaPods. This required me to covert the project to a Framework and rename it as "KeychainWrapper" is a private Apple internal framework and there was a conflict. So just an fyi for anyone who grabs my changes, some of the naming will have changed.

**Comment by jrendel** [comment]
These changes have been pulled into master.
