### ISSUE TITLE
2.0 not available on CocoaPods

### ISSUE THREAD

**Issue by gamenerds** [jrendel/SwiftKeychainWrapper#44]
When I try 'pod install'

[!] Unable to satisfy the following requirements:

- `SwiftKeychainWrapper (~> 2.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `SwiftKeychainWrapper (~> 2.0)`.

I of course tried 'pod repo update'.

**Comment by jrendel** [comment]
I have not yet pushed the changes in the dev branch (i.e. 2.0) to master yet and update cocoa pods. I'll try and get to that this week, maybe even tonight I may have time.

**Comment by jrendel** [comment]
Forgot to update this, but 2.0 has been pushed to CocoaPods for a few weeks now.

**Comment by sl-georgejimenez** [comment]
Hello jrendel, I'm getting the same error. I'm not sure if is there any problem in the repo right now?
