### ISSUE TITLE
Swift 3 Clearance

### ISSUE THREAD

**Issue by Sashom** [jrendel/SwiftKeychainWrapper#45]
It seems it has converted properly on XCode 8 for Swift 3.
However there are some warnings as XCode issues them for unused results from function calls now.
e.g. "Result of call to 'deleteKeychainSecClass' is unused"

Cheers

**Comment by Sashom** [comment]
XCode 8, beta 6 introduces a lot of changes. Mainly depecated syntax. Would be great if you could update the code.

**Comment by jrendel** [comment]
I've created a Swift2.3 and 3.0 branch to make the updates in. 

* develop/master are the 2.0 versions of the library under swift2.2 / Xcode 7. 
* Swift2.3 branch contains the basic changes needed to support Xcode 8
* Swift3.0 is in progress now making the necessary changes to move to Swift3.0. (calling this branch swift3.0_unstable as its still in progress but I want to be able to push changes as I go.)
