### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [jrendel/SwiftKeychainWrapper#46]
<img width="336" alt="screen shot 2016-08-03 at 5 55 05 pm" src="https://cloud.githubusercontent.com/assets/6511079/17381673/71fc1baa-59a3-11e6-9241-2112d9770f1e.png">
Should be something like:
> A simple static wrapper for the iOS Keychain to allow you to use it in a similar fashion to User Defaults. Written in Swift.

**Comment by jrendel** [comment]
Updated
