### ISSUE TITLE
Type KeychainWrapper has no member defaultKeychainWrapper

### ISSUE THREAD

**Issue by etayluz** [jrendel/SwiftKeychainWrapper#51]
Just installed the pod and tried using it. Got this error right away:

<img width="1040" alt="screen shot 2016-08-24 at 2 36 08 pm" src="https://cloud.githubusercontent.com/assets/1825834/17943121/20be26e6-6a08-11e6-94a9-7e61938e75e3.png">

**Comment by jrendel** [comment]
Are you using the latest version from cocoa pods? You can check by opening your workspace, and going to the SwiftKeychainWrapper in your pods project. Check the info.plist for the SwiftKeychainWrapper pod and make sure its version 2.0.0.

You can also see a sample project with usage here https://github.com/jrendel/SwiftKeychainWrapperExample.

**Comment by SirobChilokin** [comment]
@etayluz You forgot to add "import SwiftKeychainWrapper" to your class. Please check.
