### ISSUE TITLE
Please upgrade to Swift 3

### ISSUE THREAD

**Issue by crashoverride777** [jrendel/SwiftKeychainWrapper#57]
Please upgrade this project to swift 3 ASAP, it only will take a few minutes. Currently this breaks CocoaPod integration with Swift 3 and xCode 8.

**Comment by jrendel** [comment]
Sorry I started this a couple weeks ago but have been traveling. I'll be finishing this as soon as I can.

**Comment by crashoverride777** [comment]
Thank you very much.

**Comment by magonicolas** [comment]
Thanks! Would be awesome to have this updated.

**Comment by lztetreault** [comment]
Any idea when you may be completed the update?

**Comment by jrendel** [comment]
Everything has been pushed through to master at this point. However, I'm having issues uploading the new version to cocoa pods. You should be able to use the branch directly by updating your pod file like this:

pod 'SwiftKeychainWrapper', :git => 'https://github.com/jrendel/SwiftKeychainWrapper.git', :branch => 'master'

**Comment by Dbigshooter** [comment]
I'm still getting a lot errors, how come?

<img width="244" alt="sssss" src="https://cloud.githubusercontent.com/assets/6803648/18584832/9396368c-7c13-11e6-99b5-cfa32bf2bf5c.png">

**Comment by jrendel** [comment]
Are you getting those errors trying to compile the library, or in your own code while using the library?

**Comment by csgt** [comment]
For this to work, I had to use the following

`pod 'SwiftKeychainWrapper', :git=>'https://github.com/jrendel/SwiftKeychainWrapper.git', :tag=>'swift3.0_unstable'`

**Comment by bennettl** [comment]
I'm getting these errors as well
<img width="1280" alt="screen shot 2016-09-19 at 5 46 13 pm" src="https://cloud.githubusercontent.com/assets/1672224/18653814/5d12435a-7e91-11e6-9e4c-2c2cffd9c167.png">

**Comment by jrendel** [comment]
It looks like you are still using the old version of the library,  not the latest that's been updated for Swift.

Did you point your pod file directly at the master branch?  I haven't been able to update the cocoapod listing yet for the library as I'm having issues getting the automated cocoapod upload to work. You can manually point it to master and run pod update using this in your pod file:

pod 'SwiftKeychainWrapper', :git => 'https://github.com/jrendel/SwiftKeychainWrapper.git', :branch => 'master'

You should be on version 2.2 of the library after you update.

**Comment by crashoverride777** [comment]
This can be closed. Working great with Swift 3.

**Comment by lindseyvastola** [comment]
When do you plan on having the pod updated?

**Comment by jrendel** [comment]
What do you mean by updated? The Swift 3 updated pod has been available for quite awhile now.
