### ISSUE TITLE
KeychainWrapper.swift crashes

### ISSUE THREAD

**Issue by peterprokop** [jrendel/SwiftKeychainWrapper#65]
On this line:
`keychainQueryDictionary[SecAttrAccessible] = accessibility.keychainAttrValue`

![screen shot 2016-09-23 at 11 05 27](https://cloud.githubusercontent.com/assets/1475123/18826660/da19ab8a-83ce-11e6-8d53-240c4c459a72.png)

This happens very rarely, but do you have any ideas why it could happen?

**Comment by jrendel** [comment]
Do you remember what the actual crash was?

**Comment by peterprokop** [comment]
@jrendel Here's more info:
![screen shot 2016-09-26 at 14 19 26](https://cloud.githubusercontent.com/assets/1475123/18867424/6c36fc22-84a4-11e6-82f6-fd1edd836c10.png)
![screen shot 2016-09-26 at 14 19 22](https://cloud.githubusercontent.com/assets/1475123/18867423/6c3591e8-84a4-11e6-8b7d-37c134330ce8.png)

Unfortunately, couldn't reproduce it on device/simulator, so only Fabric log are available

**Comment by jrendel** [comment]
I just noticed your syntax is the old pre-swift 3 version of the library. Have you had a chance to update to Swift 3 yet?
