### ISSUE TITLE
Set-function returning false?

### ISSUE THREAD

**Issue by Dbigshooter** [jrendel/SwiftKeychainWrapper#66]
Hi there,

My code has been working fine until now, suddenly these lines returns false:

```
let ops: Bool = KeychainWrapper.defaultKeychainWrapper.set(ops, forKey: "ops")
let jop: Bool = KeychainWrapper.defaultKeychainWrapper.set(jop, forKey: "jop")
```

I use cocoapods, and this in the Podfile:

`pod 'SwiftKeychainWrapper', :git => 'https://github.com/jrendel/SwiftKeychainWrapper.git', :branch => 'master'`

Any ideas?

**Comment by Inseckto** [comment]
Same problem here...

**Comment by jrendel** [comment]
Is this happening since you upgraded to the Swift 3 version?

And is this happening on a device or on a simulator?

**Comment by Inseckto** [comment]
Yes I'm using Swift 3. It's happening just on the simulator, tested on iPad 3 (iOS 9.3.5) and so far is working properly.

**Comment by jrendel** [comment]
If you are testing on an iOS 10 simulator, you are probably hitting this issue: https://github.com/jrendel/SwiftKeychainWrapper/issues/59

**Comment by Inseckto** [comment]
That did it! I just enabled my Push Notifications for Xcode to create the entitlements file, and after that  everything's working fine (so far) on the iOS 10 simulator.

Thank you!

<img width="767" alt="screen shot 2016-09-28 at 1 18 35 pm" src="https://cloud.githubusercontent.com/assets/952909/18926677/5a89455e-857e-11e6-8eec-5aef3328a1cd.png">

**Comment by jrendel** [comment]
@Dbigshooter Was your issue with the iOS simulator as well?

**Comment by Dbigshooter** [comment]
@jrendel Apologies for the late respons, but yes, it's just in the simulator.

**Comment by jrendel** [comment]
Ok cool. Since the simulator issue is already being tracked, I'm going to close this issue: https://github.com/jrendel/SwiftKeychainWrapper/issues/59

**Comment by emericspiroux** [comment]
You must enable data protection in project capabilities : 
![capture d ecran 2016-11-21 a 17 43 41](https://cloud.githubusercontent.com/assets/8082005/20491582/2522f5d6-b012-11e6-9c2a-bb6ab91228a1.png)
