### ISSUE TITLE
2.1.0 unable to get via CocoaPods

### ISSUE THREAD

**Issue by pingd** [jrendel/SwiftKeychainWrapper#68]
There is no pod spec for SwiftKeychainWrapper 2.1.0 (https://github.com/CocoaPods/Specs/tree/master/Specs/SwiftKeychainWrapper) in CocoaPods.

Trying to get `pod 'SwiftKeychainWrapper', '~> 2.1'"` (or explicitly '2.1.0') with CP 1.0 or 1.1.0.rc2 fails with:

_[!] Unable to satisfy the following requirements:_
_\- `SwiftKeychainWrapper (~> 2.1)` required by `Podfile`_
_None of your spec sources contain a spec satisfying the dependency: `SwiftKeychainWrapper (~> 2.1)`._

**Comment by jrendel** [comment]
I had issues previously with pushing to CocoaPods and never did get this pushed. You can point the pod directly at branch Swift2.3 for the time being. I will get this pushed to CocoaPods soon.
