### ISSUE TITLE
34 Failing Tests?

### ISSUE THREAD

**Issue by perlguy99** [jrendel/SwiftKeychainWrapper#69]
I'm running Xcode 8.0 (8A218a)

I downloaded the devel branch and opened up the xcodeproj file

Everything builds fine, but when I run the tests I get 34 failures.  Basically, it looks like nothing is getting set.
- Is this a known issue?
- Do I need to make and configuration changes to make the tests work?

Thanks!

**Comment by jrendel** [comment]
Yes, this is a known issue with the iOS 10 simulator that I don't have a good solution for yet. Running unit tests with an iOS 9.3 simulator should allow them to run successfully.

I'm tracking the issue here: https://github.com/jrendel/SwiftKeychainWrapper/issues/59

**Comment by manojmahapatra** [comment]
@jrendel what you can (probably) do is to add a test host app and set it as host application in your test target. Also make sure the host app should've keychain sharing capability turned on(which will eventually add a keychain entitlement). This way at least I made sure (in one of my framework) the unit tests execute in iOS 10 simulator. 

Hope this helps!

**Comment by jrendel** [comment]
I finally got around to updating this. I added a host test app and tests are now running on iOS 10 simulators under Xcode 8.1
