### ISSUE TITLE
Fails to retrieve stored values with odd error

### ISSUE THREAD

**Issue by clayellis** [jrendel/SwiftKeychainWrapper#79]
I'm seeing an odd, intermittent error every once in a while. I'll try to retrieve a value as the app is launching (in `application(_:... didFinishLaunchingWithOptions)`) and just as it fails to retrieve the value I'll consistently get an error printed out to the console that I don't see otherwise making me believe the two are related. Here is the error:

```
2016-11-25 12:07:01.600167 (MY_APP_IDENTIFIER)[7172:1224012] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2016-11-25 12:07:01.609110 (MY_APP_IDENTIFIER)[7172:1224012] [MC] Reading from public effective user settings.
```

And sometimes (I can't seem to find a pattern) this one is printed as well:

```
2016-11-25 12:40:37.032139 (MY_APP_IDENTIFIER)[7195:1232649] [MC] Invalidating cache
```

I've been looking into this and people are attributing this message to either user permissions settings or app groups (neither of which I am using.) Have you seen this happening at all? Ideas? Like I said, it's intermittent and extremely difficult to try to debug and is causing my users quite a bit of a headache as it automatically logs them out of my app.

**Comment by clayellis** [comment]
@jrendel Any idea what might be going on here?

**Comment by jrendel** [comment]
@clayellis Sorry I forgot to answer this. I have not actually seen this myself and I can't remember if I've used the wrapper during didFinishLaunchingWithOptions or not.

**Comment by clayellis** [comment]
@jrendel Do you think it could have anything to do with being called from didFinishLaumchingWithOptions? I don't know much in detail about the Keychain.

**Comment by dtp5** [comment]
Any update on this? I'm also calling from `didFinishLaunchingWithOptions` and data loss seems to be sporadic, resulting in users getting logged out.
