### ISSUE TITLE
Minor change to Swift 3

### ISSUE THREAD

**Issue by SylarRuby** [jrendel/SwiftKeychainWrapper#81]
Swift 3 wants me to replace

 ```
KeychainWrapper.standard.remove(key: "myKey")

```

with:

```
KeychainWrapper.standard.removeObject(forKey: "myKey")

```

as `remove` is deprecated ;)

**Comment by jrendel** [comment]
Thats actually my own deprecation warning I added thats telling you that. Originally I used remove but then changed it to removeObject to be more consistent. You can see where I added the deprecation warning here: https://github.com/jrendel/SwiftKeychainWrapper/blob/develop/SwiftKeychainWrapper/KeychainWrapper.swift#L300
