### ISSUE TITLE
Odd bug

### ISSUE THREAD

**Issue by jtezanos** [jrendel/SwiftKeychainWrapper#9]
Haven't fully investigated but there is a rather odd bug with this Wrapper. Some phones will save to keychain using SwiftKeychainWrapper, others will not. There is no correlation between phones or versions, some iPhones 5s's the wrapper works, other it does not. This applies to all devices - 6, 6 plus, 4s.

To further describe - Saving to keychain in our test group worked for an iPhone 5s on 8.1.3 - on another 5s on 8.1.3 it did not. One iPhone 6 it did not work for (also on 8.1.3), on an iPhone 5 on 8.1.2 it did work. 

Bug is also not related to settings or anything related to settings within said app, it is isolated to SwiftKeychainWrapper.

**Comment by chrobakos** [comment]
Error codes or something?

**Comment by jtezanos** [comment]
None so far. I spent 2 days trying to figure out why it was happening, only things I know for sure is that setting a string using: KeychainWrapper.setString("Some String", forKey: "myKey") //or any variation\\ - and then trying to grab that set string - will result in nil only on *some devices. Very odd indeed.

**Comment by chrobakos** [comment]
in 
   setData(value: NSData, forKey keyName: String) -> Bool
we are adding item into keychain with 
   SecItemAdd(keychainQueryDictionary, nil)
and it returns OSStatus, which says how operation went. Which OSStatus number are you getting back with error?

**Comment by jrendel** [comment]
Any updates on whether or not this is still occurring? I would like to start cleaning up some of these old issues and don't really have anything to go on for this one.

**Comment by MattFlood7** [comment]
I am experiencing this issue after upgrading my project from swift 2.1 to 3.0. I have not seen this issue related to different device simulator, it happens on any simulator for me. I have upgraded to the swift 3 version of your code. Example of how I'm current using your library to store and get values:

`/* Set the username user default */
    class func setUsername(_ username:String){
        KeychainWrapper.standard.set(username, forKey: usernameKey)
    }
    
    /* Get the user defaults username. If not found return an empty string. */
    class func getUsername() -> String {
        
        var username = ""
        
        if let val = KeychainWrapper.standard.string(forKey: usernameKey) {
            username = val
        } else {
            setUsername("")
        }
        
        return username
    }`

**Comment by jrendel** [comment]
Matt are you using iOS 10 simulators? Does the issue occur on iOS 9 simulators as well?

**Comment by MattFlood7** [comment]
@jrendel I was previously running everything on iOS 9 with success. I recently switched to iOS 10 and had some issues only with the iOS 10 simulators. Dug through some more of your issues on here this morning and saw the recommendation to turn on Push Notifications and now it works fine in iOS 10 simulators.

**Comment by estebancs** [comment]
@jrendel there is a known issue in [Xcode 8.1](https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Introduction.html)

>Keychain APIs may fail to work in the Simulator if your entitlements file doesn’t contain a value for the application-identifier entitlement. To workaround this issue, add a user-defined build setting to your target named ENTITLEMENTS_REQUIRED and set the value to YES. This will cause Xcode to automatically insert an application-identifier entitlement when building. (28338972)

The returning status of `SecItemAdd(keychainQueryDictionary, nil)` is `-34018` which correspond to this description:
>Internal error when a required entitlement isn't present.

And all this is fixed in [Xcode 8.2](https://developer.apple.com/library/prerelease/content/releasenotes/DeveloperTools/RN-Xcode/Introduction.html)

>Keychain APIs work correctly in Simulator. (28338972)

**Comment by jrendel** [comment]
This issue with iOS 10 simulators should be fixed now in Xcode 8.2.
