### ISSUE TITLE
Support for Swift 3.1

### ISSUE THREAD

**Issue by Mackarous** [jrendel/SwiftKeychainWrapper#91]
Hey guys, wondering what your timeline is for Swift 3.1

**Comment by jrendel** [comment]
There's a few updates I need to get to, including the Swift 3.1 update. I'll see if I can work on it this weekend.

**Comment by eliburke** [comment]
If you can, please include your new allKeys() code in the next release. Thanks @jrendel !

**Comment by brentleyjones** [comment]
Just checking on the status of this.

**Comment by jrendel** [comment]
Just double checked for Swift 3.1 issues, there was only one warning showing up in the develop branch, so that has been fixed now. I'm working on a few updates based on outstanding issues and will hopefully push out an update soon. This will include the allKeys function.

**Comment by Ruthberg** [comment]
This seems like the right place to ask for Swift 4 support, will that be happening any time soon?

**Comment by jrendel** [comment]
Xcode 10 and Swift 4.2 are now properly supported in version 3.2 and this has been pushed to CocoaPods
