### ISSUE TITLE
Fix Readme.md : remove -> removeObject

### ISSUE THREAD

**Issue by nickeyzzz** [jrendel/SwiftKeychainWrapper#94]
let removeSuccessful: Bool = KeychainWrapper.standard.remove(key: "myKey")

should be

let removeSuccessful: Bool = KeychainWrapper.standard.removeObject(forKey: "myKey")

if I understood it the right way :)

**Comment by jrendel** [comment]
Updated in dev branch. I'm trying to find time to get to a few of these outstanding issues and will push a new version to CocoaPods when I can.
