### ISSUE TITLE
misspelled keychain in readme :)

### ISSUE THREAD

**Issue by itali43** [jrendel/SwiftKeychainWrapper#96]
"this provides a safe default for using the keycain."
Call me a grammar nazi if you will :), but I thought I'd go ahead and ping you about it.  Thanks for the excellent pod!

**Comment by jrendel** [comment]
Thanks for the heads up! I really need to get around to a bunch of these issues,  I'll hopefully get on them soon.

**Comment by jrendel** [comment]
Fixed in the develop branch. Will get into the next update.
